//! The C code generator (`ccg`): a backend that emits a standalone C program
//! from the Core ([`frontend::lowering::data`]), the ahead-of-time counterpart to
//! the tree-walking `interpreter`.
//!
//! [`emit`] runs the middle-end via [`frontend::ir::lower_modules`] (canonical
//! `Module.name` mangling, pattern-match compilation, A-normalization, De-Bruijn
//! indexing, closure conversion) and lowers the resulting IR to BLOCK FUNCTIONS
//! driven by the reified-K (CEK) machine baked into `runtime.c`. This mirrors the
//! C++ `CC`/`THxK` native backend: the continuation is an explicit heap stack, so
//! algebraic-effect handlers can capture and splice the delimited continuation,
//! and deep recursion grows the heap rather than the C stack. Compile the output
//! with any C99 compiler; running it prints the entry global exactly as `thrax
//! run` does.

mod gen;

use frontend::ir;
use frontend::lowering::data::Program;
use gen::{cstr, emit_extern_table, reachable_codes, Emitter};

/// The runtime prelude, emitted verbatim ahead of the generated code.
const RUNTIME: &str = include_str!("runtime.c");

/// The standard library's native support functions (scalar conversions), the
/// single source of truth shared with the interpreter's in-process link. Emitted
/// after the runtime so a generated program is self-contained.
const THRAXSTD: &str = include_str!("thraxstd.c");

/// A generated C program together with the symbolic `@extern` libraries it uses,
/// so a build step can turn them into link flags via [`utilities::Target`].
pub struct Emitted {
    pub source: String,
    pub libraries: Vec<String>,
}

/// Emit a complete C program for `modules` (root first) whose `main` forces every
/// global and prints `entry`, compiled for `target`. The target fixes the
/// `TARGET.*` reflection baked into the program (word size, os/arch), so a cross
/// build reports the target it was compiled for rather than the build host.
pub fn emit(
    modules: &[Program],
    entry: &str,
    kind: frontend::EntryKind,
    target: utilities::Target,
) -> String {
    emit_program(modules, entry, kind, target).source
}

/// Like [`emit`], also returning the symbolic `@extern` libraries the program
/// links against (deduplicated, in first-seen order).
pub fn emit_program(
    modules: &[Program],
    entry: &str,
    kind: frontend::EntryKind,
    target: utilities::Target,
) -> Emitted {
    let prog = ir::lower_modules(modules);
    let reachable = reachable_codes(&prog, entry);
    let (blocks, code_entry, externs) = Emitter::new(&prog, reachable.clone()).run();

    // Two resolution chains, mirroring the machine's `glob`: canonical
    // `Module.name` keys (exact), and bare last-segment names (first definition
    // winning), for an unqualified reference or the entry point.
    let canon: Vec<(&str, usize)> = prog.globals.iter().map(|(n, c)| (n.as_str(), *c)).collect();
    let mut bare: Vec<(&str, usize)> = Vec::new();
    for (name, code) in &prog.globals {
        let last = name.rsplit('.').next().unwrap_or(name);
        if !bare.iter().any(|(n, _)| *n == last) {
            bare.push((last, *code));
        }
    }

    let mut out = String::new();
    out.push_str(
        "/* Generated by the Thrax ccg backend. Do not edit. Self-contained;\n\
         \x20* the runtime is inlined below. Build: cc -O2 prog.c -o prog */\n\n",
    );
    let (int_max, int_min) = if target.ptr_bits() == 32 {
        ("0x7fffffffLL", "(-0x7fffffffLL - 1)")
    } else {
        ("0x7fffffffffffffffLL", "(-0x7fffffffffffffffLL - 1)")
    };
    out.push_str(&format!(
        "#define THRAX_ARCH {}\n",
        cstr(target.arch_name().as_bytes())
    ));
    out.push_str(&format!("#define THRAX_OS {}\n", cstr(target.os_name().as_bytes())));
    out.push_str(&format!("#define THRAX_INT_BITS {}\n", target.ptr_bits()));
    out.push_str(&format!("#define THRAX_INT_MAX {int_max}\n"));
    out.push_str(&format!("#define THRAX_INT_MIN {int_min}\n"));
    out.push_str(RUNTIME);
    out.push_str(THRAXSTD);

    // Globals: lazily forced, memoized CAFs (matches the machine's `glob`). Memo
    // is keyed by code index, so a global reached by its canonical and bare names
    // is evaluated once.
    out.push_str("\n/* -- globals -- */\n");
    let ncodes = prog.codes.len();
    out.push_str(&format!("static Value* g_cache[{}];\n", ncodes.max(1)));
    out.push_str(&format!("static char g_inited[{}];\n", ncodes.max(1)));
    out.push_str(&format!("static char g_inprog[{}];\n", ncodes.max(1)));
    out.push_str("static Value* force_code(size_t code) {\n");
    out.push_str("  if (g_inited[code]) return g_cache[code];\n");
    out.push_str("  if (g_inprog[code]) thrax_fault(\"cyclic value global\");\n");
    out.push_str("  g_inprog[code] = 1;\n");
    out.push_str("  g_cache[code] = THxK_run_code(code);\n");
    out.push_str("  g_inited[code] = 1;\n");
    out.push_str("  g_inprog[code] = 0;\n");
    out.push_str("  return g_cache[code];\n");
    out.push_str("}\n");
    out.push_str("Value* THxRT_glob(const char* name) {\n");
    for (name, code) in canon.iter().chain(bare.iter()) {
        out.push_str(&format!(
            "  if (strcmp(name, {}) == 0) return force_code({code});\n",
            cstr(name.as_bytes())
        ));
    }
    out.push_str("  thrax_fault(\"unbound global\");\n");
    out.push_str("}\n\n");

    // Forward declarations of every block, then the definitions (blocks reference
    // each other's continuations freely).
    out.push_str("/* -- blocks -- */\n");
    for i in 0..blocks.len() {
        out.push_str(&format!("static void blk_{i}(Frame*, Value*);\n"));
    }
    out.push('\n');
    for b in &blocks {
        out.push_str(b);
    }

    // The foreign-function wrappers and their dispatch table (empty table + count
    // 0 when the program has no `@extern`).
    out.push_str(&emit_extern_table(&externs, &prog.crepr_layouts));

    // The dispatch tables the runtime calls back through: entry block + slot count
    // per lifted Code.
    out.push_str("/* -- code tables -- */\n");
    out.push_str("BlockFn THxRT_code_table[] = {\n");
    for &e in &code_entry {
        out.push_str(&format!("  blk_{e},\n"));
    }
    out.push_str("};\n");
    out.push_str("const size_t THxRT_code_nlocals[] = {\n");
    for c in &prog.codes {
        out.push_str(&format!("  {},\n", c.nlocals));
    }
    out.push_str("};\n");
    out.push_str(&format!("const size_t THxRT_code_count = {ncodes};\n\n"));

    // Entry. A value is forced and printed (`entry = <value>`), with the built-in
    // leak check (exit 97 on a leak). A C-style `main` is applied to unit or to the
    // argument vector `[n]Str`, and its `Int` result is the process exit code.
    out.push_str("int main(int argc, char** argv) {\n");
    out.push_str("  (void)argc; (void)argv;\n");
    for (name, code) in &canon {
        // Force only globals reachable from the entry (the interpreter is entry-
        // lazy; an unreachable global's CAF is a trap stub).
        if reachable.contains(code) {
            out.push_str(&format!("  (void)THxRT_glob({});\n", cstr(name.as_bytes())));
        }
    }
    let entry_c = cstr(entry.as_bytes());
    match kind {
        frontend::EntryKind::Value => {
            out.push_str(&format!("  Value* e = THxRT_glob({entry_c});\n"));
            out.push_str("  char* shown = thrax_show(e);\n");
            out.push_str(&format!("  printf(\"%s = %s\\n\", {entry_c}, shown);\n"));
            out.push_str("  free(shown);\n");
            out.push_str("  for (size_t c = 0; c < THxRT_code_count; c++)\n");
            out.push_str("    if (g_inited[c]) THxMEM_release(g_cache[c]);\n");
            out.push_str("  THxMEM_pool_drain(0);\n");
            out.push_str("  size_t live = THxMEM_live();\n");
            out.push_str("  THxRT_shutdown();\n");
            out.push_str("  if (live != 0) {\n");
            out.push_str(
                "    fprintf(stderr, \"thrax: %zu live allocations at exit (leak)\\n\", live);\n",
            );
            out.push_str("    return 97;\n");
            out.push_str("  }\n");
            out.push_str("  return 0;\n");
        }
        frontend::EntryKind::UnitFn | frontend::EntryKind::ArgvFn => {
            if kind == frontend::EntryKind::ArgvFn {
                // Build a `[n]Str` from the C argument vector.
                out.push_str("  Value** _items = (Value**)malloc((size_t)(argc>0?argc:1)*sizeof(Value*));\n");
                out.push_str("  for (int _i = 0; _i < argc; _i++) _items[_i] = THxRT_str(argv[_i], strlen(argv[_i]));\n");
                out.push_str("  Value* _arg = tensor_stack(_items, (size_t)argc);\n");
                out.push_str("  free(_items);\n");
            } else {
                out.push_str("  Value* _arg = THxRT_unit();\n");
            }
            out.push_str(&format!(
                "  Value* e = THxK_call(THxRT_glob({entry_c}), _arg);\n"
            ));
            out.push_str("  int _code = (int)THxVALUE_as_int(e);\n");
            out.push_str("  return _code;\n");
        }
        frontend::EntryKind::BadFn => unreachable!("rejected before emit"),
    }
    out.push_str("}\n");

    // The runtime's `arith` calls `pow` (real `^`), so every native binary links
    // libm. (`link_flag` maps "m" to `-lm`; on emcc it is a harmless no-op.)
    let mut libraries: Vec<String> = vec!["m".to_string()];
    for e in &externs {
        if !libraries.iter().any(|l| l == &e.lib) {
            libraries.push(e.lib.clone());
        }
    }
    // A program that passes a Thrax closure to C uses libffi closures, so it must
    // link libffi (the generated callback runtime includes `<ffi.h>`).
    let uses_callbacks = externs
        .iter()
        .any(|e| e.arg_types.iter().any(|t| t.starts_with("@fn(")));
    if uses_callbacks && !libraries.iter().any(|l| l == "ffi") {
        libraries.push("ffi".to_string());
    }
    Emitted {
        source: out,
        libraries,
    }
}
