CXX      = clang++
CXXFLAGS = -Wall -Wextra -Wimplicit-fallthrough -Werror -g -Iinc -MMD -MP

Tthrax = bin/thrax
Ttest  = bin/tst_all

# The C runtime, amalgamated into a generated header and baked into the compiler
# so emitted programs are self-contained (see the $(GEN_HDR) rule, CC.cpp).
# Headers first (inclusion order), then sources.
RT_FILES = inc/THxCHECK.h inc/THxVALUE.h inc/THxMEM.h inc/THxRT.h inc/THxK.h \
           src/THxCHECK.c src/THxVALUE.c src/THxMEMBUMP.c src/THxRT.c src/THxK.c
GEN_HDR  = inc/THxRTxAMALG.hpp

ifdef THRAX_3RD_PARTY_ON
CXXFLAGS += -I$(LIBFFI_DEV)/include
LIBS     += -L$(LIBFFI)/lib -lffi -ldl -Wl,-rpath,$(LIBFFI)/lib
CXXFLAGS += -DTHRAX_3RD_PARTY_ON=1
endif

all: $(Tthrax) $(Ttest) compile_flags.txt

# Amalgamate the runtime into a generated header baked into the compiler: wrap
# the runtime files (inter-runtime `#include "THx*.h"` stripped -- everything is
# inline; system includes kept) in a raw string `CC::RUNTIME_C`. CC::emit
# prepends it so every emitted program is self-contained.
$(GEN_HDR): $(RT_FILES)
	@printf '/* Generated by the makefile from the runtime. Do not edit. */\n' > $@
	@printf '#ifndef THxRTxAMALG_HEADER_\n#define THxRTxAMALG_HEADER_\n' >> $@
	@printf 'namespace CC\n{\n' >> $@
	@printf 'inline const char RUNTIME_C[] = R"THXRTAMALG(\n' >> $@
	@grep -hv -E '^[[:space:]]*#[[:space:]]*include[[:space:]]*"THx' $(RT_FILES) >> $@
	@printf ')THXRTAMALG";\n} // namespace CC\n#endif // THxRTxAMALG_HEADER_\n' >> $@

# --- PCH Configuration ---
PCH_SRC = $(wildcard inc/*.hpp)
PCH_OUT = bin/UTxAMALG.hpp.pch
PCH_FLAGS = -Xclang -include-pch -Xclang $(PCH_OUT)

# Rule to compile PCH binary. The generated runtime header is an order-only
# prerequisite so it exists before the unity build, without becoming `$<`.
$(PCH_OUT): $(PCH_SRC) | bin $(GEN_HDR)
	$(CXX) $(CXXFLAGS) -x c++-header $< -o $@

# --- Object rules ---
OBJS = bin/UTxAMALG.o bin/TS.o bin/main.o bin/tst_all.o
-include $(OBJS:.o=.d)

bin/UTxAMALG.o: src/UTxAMALG.cpp $(PCH_OUT) $(GEN_HDR) | bin
	$(CXX) $(CXXFLAGS) $(PCH_FLAGS) -c $< -o $@

bin/TS.o: tst/TS.cpp $(PCH_OUT) | bin
	$(CXX) $(CXXFLAGS) $(PCH_FLAGS) -c $< -o $@

bin/main.o: src/main.cpp $(PCH_OUT) | bin
	$(CXX) $(CXXFLAGS) $(PCH_FLAGS) -c $< -o $@

bin/tst_all.o: tst/tst_all.cpp $(PCH_OUT) | bin
	$(CXX) $(CXXFLAGS) $(PCH_FLAGS) -c $< -o $@

# --- Linking Rules ---
$(Tthrax): bin/main.o bin/UTxAMALG.o | bin
	$(CXX) $(CXXFLAGS) $^ $(LIBS) -o $@

$(Ttest): bin/tst_all.o bin/TS.o bin/UTxAMALG.o | bin
	$(CXX) $(CXXFLAGS) $^ $(LIBS) -o $@

bin: ; mkdir -p bin

compile_flags.txt: makefile | bin
	@printf '%s\n' $(CXXFLAGS) > $@
	@printf '%s\n' "-I./inc/" >> $@

# --- Utility commands ---
.PHONY: test native-test clean format tokei executables valgrind

clean:                ; rm -rf bin tmp.* vgcore* *.orig compile_flags.txt $(GEN_HDR)
format:               ; clang-format -i src/*.cpp src/*.c inc/*.hpp inc/*.h tst/*.cpp tst/*.hpp
tokei:                ; tokei --exclude lib
valgrind: bin/tst_all ; valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./bin/tst_all

# The test logic lives in tst/makefile; these targets build the binaries it needs
# and delegate to it (so `make test` / `make native-test` still work from root).
test:        $(Ttest)            ; $(MAKE) -C tst test
native-test: $(Tthrax) $(Ttest)  ; $(MAKE) -C tst native-test
