[package]
name = "thrax"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "thrax"
path = "src/main.rs"

[dependencies]
utilities = { path = "../utilities" }
frontend = { path = "../frontend" }
interpreter = { path = "../interpreter" }
ccg = { path = "../ccg" }
