name: Makefile CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - name: Run make in Nix dev shell
        run: |
          nix develop --command bash -c '
            make format
            make
          '

