// Headless smoke test for the browser build (`build wasm`): load the compiled
// playground module in Node exactly as the page does, run a few programs
// through `thrax_eval`, and assert their output. Exits non-zero on any
// mismatch. Run from the repo root after `build wasm`:  node web/smoke.mjs
//
// This guards the whole Emscripten path -- the amalgam compiling under emcc,
// the host-table FFI (C.puts / math), and the ccall bridge -- without a
// browser.

import createThrax from "./site/thrax.js";

// [name, mode, source, expected-substrings-in-stdout]
const CASES = [
  ["hello", 0,
    `@mod MAIN\n\n$ main : Int =\n\tC.puts "hi"; 0\n`,
    ["hi"]],
  ["fib", 0,
    `@mod MAIN\n\n$ with STR\n\n$ fib : Int -> Int = \\n =\n\tif n ?< 2 then n\n\telse fib (n - 1) + fib (n - 2)\n\n$ main : Int =\n\tC.puts (STR.from_int (fib 20)); 0\n`,
    ["6765"]],
  ["math (host table)", 0,
    `@mod MAIN\n\n$ with MATH\n\n$ main : Int =\n\tif sqrt 144.0 ?= 12.0 then (C.puts "sqrt ok"; 0) else 1\n`,
    ["sqrt ok"]],
  ["target reflection", 0,
    `@mod MAIN\n\n$ main : Int =\n\tC.puts TARGET.name; 0\n`,
    ["wasm32"]],
  ["emit C", 1,
    `@mod MAIN\n\n$ main : Int = 0\n`,
    ["Generated by the Thrax CC backend"]],
];

let failures = 0;

for (const [name, mode, src, wants] of CASES) {
  const out = [];
  const M = await createThrax({
    print: (s) => out.push(s),
    printErr: (s) => out.push("[err] " + s),
  });
  let rc;
  try {
    rc = M.ccall("thrax_eval", "number", ["string", "number"], [src, mode]);
  } catch (e) {
    console.error(`FAIL ${name}: runtime threw ${e}`);
    failures++;
    continue;
  }
  const text = out.join("\n");
  const missing = wants.filter((w) => !text.includes(w));
  if (rc !== 0 || missing.length) {
    console.error(
      `FAIL ${name}: rc=${rc}, missing ${JSON.stringify(missing)}\n${text}`,
    );
    failures++;
  } else {
    console.log(`ok   ${name}`);
  }
}

if (failures) {
  console.error(`web/smoke: ${failures} case(s) failed`);
  process.exit(1);
}
console.log("web/smoke: OK -- the browser build runs");
